apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0
          args: ["start-dev", "--import-realm"]
          ports:
            - containerPort: 8080
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres:5432/keycloak
            - name: KC_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: collector-config
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: collector-config
                  key: POSTGRES_PASSWORD
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: collector-config
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: collector-config
                  key: KEYCLOAK_ADMIN_PASSWORD
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
  volumes:
    - name: realm-config
      hostPath:
        path: /home/ton-ami/collector/keycloak
        type: Directory