apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: collector
data:
  POSTGRES_DB: collector
  POSTGRES_USER: collector_user
  POSTGRES_PASSWORD: collector_pass
  RABBITMQ_USER: collector_user
  RABBITMQ_PASSWORD: collector_pass
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin123
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/collector
  SPRING_RABBITMQ_HOST: rabbitmq
  KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/collector
  CLOUDINARY_CLOUD_NAME: djwtlaqgu
  CLOUDINARY_API_KEY: "792766976773666"